package/glibc/switch to git protocol
We have a random issue while fetching the git repo using http/https.

>>> glibc glibc-2.26-65-ga76376df7c07e577a9515c3faa5dbd50bda5da07 Downloading
Doing full clone
Cloning into glibc-glibc-2.26-65-ga76376df7c07e577a9515c3faa5dbd50bda5da07...
error: Failed connect to sourceware.org:443; No such file or directory (curl_result = 7, http_code = 0, sha1 = c39cf238b67d65b0343d88d7cbbfab87f0925162)
error: Unable to find c39cf238b67d65b0343d88d7cbbfab87f0925162 under https://sourceware.org/git/glibc.git
Cannot obtain needed object c39cf238b67d65b0343d88d7cbbfab87f0925162
while processing commit 15b7cc7d742ff60d09f0638ce53e66e546e3eab5.
error: Fetch failed.

Signed-off-by: Romain Naour <romain.naour@gmail.com>