boot/grub2: use GRUB_FILE_TYPE_NO_DECOMPRESS
Backport upstream patch [1] to use GRUB_FILE_TYPE_NO_DECOMPRESS instead of FILE_TYPE_NO_DECOMPRESS.

"Blocklist fallout cleanup after commit 5c6f9bc15 (generic/blocklist: Fix
implicit declaration of function grub_file_filter_disable_compression())."

Fixes:
grub-core/osdep/generic/blocklist.c:62:67: error: 'FILE_TYPE_NO_DECOMPRESS' undeclared (first use in this function);
   62 |       file = grub_file_open (core_path_dev, GRUB_FILE_TYPE_NONE | FILE_TYPE_NO_DECOMPRESS);

[1] https://git.savannah.gnu.org/cgit/grub.git/commit/?id=dabdfa1c6a80639197d05f683a445fa8615517fe

Signed-off-by: Romain Naour <romain.naour@gmail.com>