toolchain: enable libquadmath for powerpc64(le)
When gfortran is enabled on powerpc64(le) we need to build the
libquiadmath library provided by GCC since this architecture
now support 128-bit floating point (__float128) values.

Otherwise the build break due to missing header:
In file included from ../../../libgfortran/runtime/string.c:25:
../../../libgfortran/libgfortran.h:61:12: fatal error: quadmath_weak.h: No such file or directory
   61 | #  include "quadmath_weak.h"
      |            ^~~~~~~~~~~~~~~~~

This support has been merged into gcc since release 8.1 [1][2].

This issue was not noticed before because the Fortran support
wasn't enabled in the toolchain-builder project until recently [3].

Update comment in pkg-toolchain-external.mk.

Fixes:
https://gitlab.com/kubu93/toolchains-builder/-/jobs/771109960 (powerpc64)
https://gitlab.com/kubu93/toolchains-builder/-/jobs/771109993 (powerpc64le)

[1] https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/PowerPC-Built-in-Functions.html
[2] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85440
[3] https://github.com/bootlin/toolchains-builder/commit/ee958c9c587334f08de695886a8279383a4382da

Signed-off-by: Romain Naour <romain.naour@gmail.com>