package/efl/libefl: new package
Add the libefl package which contains an updated version of the following
libraries:
libecore, libedje, libeet, libfreet, libeina, libeio, libembryo, libthumb
and libevas. It also contains eldbus, ephysics, and escape, see [1].

The name libefl is transitional in order to bump smoothly all packages
that use efl libraries and remove the old package libecore, libevas...
The package libefl will be renamed to efl in a followup patch at the end
of the series.

For now, the bump to efl 1.15.x is not complete.
This allows to build at least a default configuration without X11 support
or graphics acceleration.
This support will be added by a follow up patches in the series.

Also, add BR2_PACKAGE_LIBEFL_RECOMMENDED_CONFIG config option in order to
select all recommended packages that allows to build libefl without the
extra-long --enable-i-really-know-what-i-am-doing...

Here is some notes about libefl dependencies:
  - alsa:
    At the end of the configure script, the summary tab will show that
    alsa support is allways disabled even if alsa-utils has been build
    before efl-core package.
    "Ecore_Audio.....: yes (-alsa +pulseaudio +sndfile)"
    This is intentional.

  - util-linux:
    libefl select util-linux libblkid since it's listed as an dependency
    in the README [2].

  - threads support:
    Add a dependency on threads support since clearly efl libraries are
    not even built without thread support [3].

  - Curl:
    Curl is listed as an dependency in the README because it's a runtime
    dependency since efl 1.8 [4].

We need to regenerate the configure script to workaround a build issue with
eldbus-codegen:

  CCLD     bin/eldbus/eldbus-codegen
  CXXLD    bin/eolian_cxx/eolian_cxx
  CCLD     lib/ecore_x/ecore_x_vsync
  CCLD     lib/evas/common/libevas_op_blend_sse3.la
  CCLD     lib/evas/common/libevas_convert_rgb_32.la
  CCLD     lib/ecore_ipc/libecore_ipc.la
[...]/i686-ctng-linux-gnu/bin/ld: warning: libefl.so.1, needed by lib/ecore/.libs/libecore.so, not found (try using -rpath or -rpath-link)
lib/ecore/.libs/libecore.so: undefined reference to `efl_control_suspend_set'
lib/ecore/.libs/libecore.so: undefined reference to `efl_control_interface_get'
collect2: error: ld returned 1 exit status
Makefile:19135: recipe for target 'bin/eldbus/eldbus-codegen' failed
make[6]: *** [bin/eldbus/eldbus-codegen] Error 1

A dependency on libefl seems to be missing for eldbus but by
regenerating eldbus-codegen build correctly.

Reported upstream [6].

Also, gettextize is needed since *.po files were generated with
an "old" gettext version (0.18):

Making all in po
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19
Makefile:149: recipe for target 'check-macro-version' failed

[1] See https://phab.enlightenment.org/phame/live/3/post/efl_1_8/
[2] https://git.enlightenment.org/core/efl.git/tree/README?id=v1.15.2#n478
[3] https://git.enlightenment.org/core/efl.git/tree/configure.ac#n5032
[4] https://git.enlightenment.org/core/efl.git/tree/README?id=v1.15.2#n453
    https://git.enlightenment.org/core/efl.git/commit/?id=2c1c6b9335e38c6e52b06829a95d9b58d780c99e
[5] http://mailman.uclibc-ng.org/pipermail/devel/2015-August/000432.html
[6] https://phab.enlightenment.org/T2718

Signed-off-by: Romain Naour <romain.naour@openwide.fr>
Tested-by: Vicente Bergas <vicencb@gmail.com>
Cc: Vicente Bergas <vicencb@gmail.com>
---
An initial runtime test has been done under Qemu with a glibc x86 toolchain.

An additional runtime test has been done with a uClibc-ng 1.0.5 toolchain
patched with [5] in order to add mkstemps() which is used by Eina library.
This patch has been upstreamed in uClubc-ng 1.0.6 release.

Another test has been done with a musl toolchain by Vicente Bergas (Thanks!).
---
v11:
    - add Config.in options for each recommended dependencies. (Thomas P)
    - fix Lua Config.in comment dependency (Thomas P)
    - Avoid duplicate dependencies between BR2_PACKAGE_EFL and BR2_PACKAGE_LIBEFL
     (Thomas P)
    - Rework commit log to explain that BR2_PACKAGE_EFL menuconfig will become a
      real Buildroot package by renaming libefl to efl.
v10:
    - fix typo configurations -> configuration
    - fix lua/dependencies comments handling in Config.in

v8: move comments about the runtime test to post-commit note (Yann E.Morin)
    remove comment about X11 XInput v2.2+ support.
    Add the tested-by tag from Vicente Bergas
v6: Changes from Yann E.Morin's review
     - squash curl, autotools and libblkid patches
     - use depends on Lua
     - LIBEFL_RECOMMENDED_CONFIG depends on BR2_ARCH_HAS_ATOMICS
     - rework Config.in help text (remove comments in .mk)
     - add some option in LIBEFL_CONF_OPTS to disable some features
       explicitely.
    Split the dependency comment (Arnout)

v4: rename to libefl
    EFL needs a toolchain with threads support
v3: fix same typo again
    Add a note about multisense support
v2: remove glibc only dependency
    update commit log accordingly
    fix typo in Config.in (Vicente Bergas)