configs/qemu_ppc64(le)_pseries: add kernel patch to fix gcc 11.x build issue
With gcc 11.x, the PPC64(LE) kernel for pseries fails to build with:

Cannot find symbol for section 11: .text.unlikely.
kernel/kexec_file.o: failed
scripts/Makefile.build:277: recipe for target 'kernel/kexec_file.o' failed

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 39323c63306af6e632fb0c17950a137948d29193)
Signed-off-by: Romain Naour <romain.naour@gmail.com>