WIP: localedef build issue with old glibc (<= 2.38)
While building localdef from glibc sources, it uses the features.h
header that define _ISOC2X_SOURCE 1 as soon as _GNU_SOURCE is defined.

_ISOC2X_SOURCE enable __GLIBC_USE_ISOC2X 1 that enable the header
redirection to use __isoc23_* functions introduced in glibc 2.38.

If an older version is installed on the host thoses functions
doesn't exist and break the build.

Add a local patch to keep _ISOC2X_SOURCE and __GLIBC_USE_ISOC2X
disabled.

Fixes:
host-localedef-2.38-13-g92201f16cbcfd9eafe314ef6654be2ea7ba25675/build/locale/ld-ctype.o: in function `ctype_read':
ld-ctype.c:(.text+0x6cef): undefined reference to `__isoc23_strtoul'

(glibc 2.31 installed on the host)

[1] https://sourceware.org/git/?p=glibc.git;a=commit;h=64924422a99690d147a166b4de3103f3bf3eaf6c

Signed-off-by: Romain Naour <romain.naour@gmail.com>